services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: yourVeryStrongPassword
      POSTGRES_DB: v3db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 1883"]
      interval: 2s
      timeout: 2s
      retries: 5
    volumes:
      - ./mosquitto-config/:/mosquitto/config


  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: "postgresql://admin:adminPassword@db:5432/v3db"
      MQTT_BROKER: mqtt
      MQTT_PORT: 1883
      FLASK_APP: BackendAppPMB.py
      FLASK_ENV: development
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mqtt
    volumes:
      - ./backend:/app

volumes:
  pgdata:
