FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY ["Back End/requirements.txt", "requirements.txt"]
RUN pip install --no-cache-dir -r requirements.txt

# Copy simulator code
COPY ["Back End/MQTTSimulator.py", "."]

CMD ["python", "MQTTSimulator.py"]