FROM python:3.9-slim

WORKDIR /app

# Copy dependencies first
COPY ["Back End/requirements.txt", "requirements.txt"]

RUN pip install --no-cache-dir -r requirements.txt

# Now copy all required source folders
COPY ["Database/", "Database/"]
COPY ["Back End/", "."]

EXPOSE 8080

CMD ["python", "PMBAppBackEnd.py"]